[package]
name = "hash_table_open_addressing"
version = "0.1.0"
authors = ["Howard Huang <howeih@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7.2"